import 'package:flutter/foundation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import '../models/category.dart';
import '../models/transaction.dart';
import 'supabase_config.dart';

/// A natural-language money tip generated by the AI coach.
@immutable
class AiTip {
  const AiTip({
    required this.title,
    required this.detail,
    this.categoryId,
    this.potentialSaving = 0,
  });

  final String title;
  final String detail;
  final String? categoryId;
  final double potentialSaving;

  factory AiTip.fromJson(Map<String, dynamic> j) => AiTip(
        title: (j['title'] ?? '').toString(),
        detail: (j['detail'] ?? '').toString(),
        categoryId: (j['category'] as String?)?.toLowerCase(),
        potentialSaving: (j['potentialSaving'] as num?)?.toDouble() ?? 0,
      );
}

/// Outcome of an AI request, so the UI can show a precise message.
enum AiStatus { ok, empty, notEnoughData, notConfigured, error }

@immutable
class AiResult {
  const AiResult({required this.status, required this.tips});
  final AiStatus status;
  final List<AiTip> tips;
}

/// Calls the `ai-insights` Edge Function with an aggregated spending summary
/// and returns AI-written tips. Only non-identifying aggregates are sent; the
/// model/key live server-side.
class AiInsightsService {
  AiInsightsService._();
  static final AiInsightsService instance = AiInsightsService._();

  SupabaseClient? get _client {
    if (!SupabaseConfig.isConfigured) return null;
    try {
      return Supabase.instance.client;
    } catch (_) {
      return null;
    }
  }

  /// Builds the summary from transactions and asks the AI for tips.
  /// Returns an [AiResult] with a status so the UI can always show a clear
  /// message (never a blank screen).
  Future<AiResult> generate(List<Transaction> txns, {DateTime? now}) async {
    final client = _client;
    if (client == null || client.auth.currentUser == null) {
      return const AiResult(status: AiStatus.error, tips: []);
    }

    final ref = now ?? DateTime.now();
    final summary = _buildSummary(txns, ref);
    if (summary == null) {
      return const AiResult(status: AiStatus.notEnoughData, tips: []);
    }

    try {
      final res = await client.functions.invoke('ai-insights', body: summary);
      final data = res.data;
      if (data is Map && data['configured'] == false) {
        return const AiResult(status: AiStatus.notConfigured, tips: []);
      }
      if (data is Map && data['tips'] is List) {
        final tips = (data['tips'] as List)
            .whereType<Map>()
            .map((m) => AiTip.fromJson(Map<String, dynamic>.from(m)))
            .where((t) => t.title.isNotEmpty)
            .toList();
        return AiResult(
          status: tips.isEmpty ? AiStatus.empty : AiStatus.ok,
          tips: tips,
        );
      }
    } catch (e) {
      debugPrint('AiInsightsService.generate failed: $e');
    }
    return const AiResult(status: AiStatus.error, tips: []);
  }

  Map<String, dynamic>? _buildSummary(List<Transaction> txns, DateTime ref) {
    final thisStart = DateTime(ref.year, ref.month);
    final thisEnd = DateTime(ref.year, ref.month + 1);

    double income = 0, expense = 0;
    final catThis = <String, double>{};
    for (final t in txns) {
      if (t.date.isBefore(thisStart) || !t.date.isBefore(thisEnd)) continue;
      if (t.isCredit) {
        income += t.amount;
      } else {
        expense += t.amount;
        catThis.update(t.categoryId, (v) => v + t.amount,
            ifAbsent: () => t.amount);
      }
    }
    if (expense <= 0) return null;

    // 3-month average per category.
    final catAvg = <String, double>{};
    for (var m = 1; m <= 3; m++) {
      final s = DateTime(ref.year, ref.month - m);
      final e = DateTime(ref.year, ref.month - m + 1);
      for (final t in txns) {
        if (t.isCredit) continue;
        if (t.date.isBefore(s) || !t.date.isBefore(e)) continue;
        catAvg.update(t.categoryId, (v) => v + t.amount / 3,
            ifAbsent: () => t.amount / 3);
      }
    }

    final categories = catThis.entries.map((e) {
      return {
        'category': Categories.byId(e.key).name,
        'thisMonth': double.parse(e.value.toStringAsFixed(0)),
        'avg3Month': double.parse((catAvg[e.key] ?? 0).toStringAsFixed(0)),
      };
    }).toList();

    return {
      'currency': 'INR',
      'income': double.parse(income.toStringAsFixed(0)),
      'expense': double.parse(expense.toStringAsFixed(0)),
      'categories': categories,
    };
  }
}
